In [1]:
import numpy as np

In [8]:
np.linspace(0, 3, 4)

array([0., 1., 2., 3.])

In [32]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape) # 2 x 120
weight_size = output_dim * np.prod(input_shape) # 3 x 120

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)


In [33]:
x.shape

(2, 4, 5, 6)

In [57]:
np.random.seed(231)
x = np.random.randn(10, 2, 3)
w = np.random.randn(6, 5)
b = np.random.randn(5)
dout = np.random.randn(10, 5)

In [58]:
dx = np.dot(dout, w.T)

In [59]:
dx = dx.reshape((x.shape))

In [60]:
dx = np.dot(dout, w.T).reshape((x.shape))
dw = np.dot(x.T, dout)
db = np.sum(dout, axis=0, keepdims=True)


In [61]:
dx.shape
dw.shape
# db.shape

(3, 2, 5)

In [66]:
np.random.seed(231)
x = np.random.randn(10, 10)
dout = np.random.randn(*x.shape)

In [74]:
x

array([[ 0.41794341,  1.39710028, -1.78590431, -0.70882773, -0.07472532,
        -0.77501677, -0.1497979 ,  1.86172902, -1.4255293 , -0.3763567 ],
       [-0.34227539,  0.29490764, -0.83732373,  0.95218767,  1.32931659,
         0.52465245, -0.14809998,  0.88953195,  0.12444653,  0.99109251],
       [ 0.03514666,  0.26207083,  0.14320173,  0.90101716,  0.23185863,
        -0.79725793,  0.12001014, -0.65679608,  0.26917456,  0.333667  ],
       [ 0.27423503,  0.76215717, -0.69550058,  0.29214712, -0.38489942,
         0.1228747 , -1.42904497,  0.70286283, -0.85850947, -1.14042979],
       [-1.58535997, -0.01530138, -0.32156083,  0.56834936, -0.19961722,
         1.27286625,  1.27292534,  1.58102968, -1.75626715,  0.9217743 ],
       [-0.6753054 , -1.43443616,  0.47021125,  0.03196734,  0.04448574,
         0.47824879, -2.51335181, -1.15740245, -0.70470413, -1.04978879],
       [-1.90795589,  0.49258765,  0.83736166, -1.4288134 , -0.18982427,
        -1.14094943, -2.12570755, -0.41354791

In [84]:
sig = 1 / (1 + np.exp(-5))
print(sig)

0.9933071490757153


In [96]:
arry = 4*np.random.randn(200000000)

In [97]:
np.std(arry)

3.9999036551150557

In [105]:
np.random.seed(231)
N, D, H, C = 3, 5, 50, 7
x = np.random.randn(N, D)
# y = np.random.randint(C, size=N)

In [106]:
y = np.asarray([0, 5, 1])

In [107]:
N = X.shape[0]

In [117]:
h = np.zeros((100,1))
h.shape

(100, 1)

In [109]:
shifted_logits = x - np.max(x, axis=1, keepdims=True)
Z = np.sum(np.exp(shifted_logits), axis=1, keepdims=True)
log_probs = shifted_logits - np.log(Z)
probs = np.exp(log_probs)
N = x.shape[0]


loss = -np.sum(log_probs[np.arange(N), y]) / N
dx = probs.copy()
dx[np.arange(N), y] -= 1
dx /= N

IndexError: index 5 is out of bounds for axis 1 with size 5

In [13]:
num_layers = 2
for layer in range(num_layers):
    myvar = "var" + str(layer)
    print(myvar)

var0
var1


In [43]:
for i in range(1,num_layers):
    print(i)

1


In [58]:
num_layers = 3

In [59]:
for layer in range(1, num_layers+1):
    print(layer)

1
2
3


In [61]:
# for layer in range(1, num_layers):
#     print(layer)

for layer in range(num_layers, 1):
    print(layer)

In [62]:
mylist = [1, 2, 3, 4]

In [69]:
for layer in range(1, num_layers+1)[::-1]:
    if layer == num_layers:
        print('Ahhhhhhhh')
    print(layer)

Ahhhhhhhh
3
2
1


In [71]:
W1 = np.array(([1,2],[5,6]))

In [77]:
W1

array([[1, 2],
       [5, 6]])

In [78]:
W1 * W1

array([[ 1,  4],
       [25, 36]])

In [1]:
## Batch Norm

In [45]:
x = np.random.randn(10,2)
b = np.arange(10).reshape((10,1))
xhat = x+b

In [46]:
xhat

array([[-1.26396151,  1.11246304],
       [ 0.95599566, -0.19358847],
       [ 1.37296253,  2.15470537],
       [ 0.60477567,  3.58020233],
       [ 2.93673833,  6.26562234],
       [ 3.41184285,  6.26107401],
       [ 6.12962393,  5.90081494],
       [ 8.30788985,  7.03090265],
       [ 6.83482153,  9.35846044],
       [ 9.90551729,  9.89907038]])

In [47]:
batch_mean = np.mean(xhat, axis=1)
batch_mean

array([-0.07574923,  0.38120359,  1.76383395,  2.092489  ,  4.60118033,
        4.83645843,  6.01521943,  7.66939625,  8.09664098,  9.90229383])

In [49]:
batch_var = np.var(xhat, axis=1)
batch_var

array([1.41184841e+00, 3.30385915e-01, 1.52780465e-01, 2.21329095e+00,
       2.77036718e+00, 2.02952955e+00, 1.30883894e-02, 4.07674080e-01,
       1.59218833e+00, 1.03906584e-05])

In [52]:
c = np.arange(10,20)

In [56]:
x = np.arange(12).reshape((4,3))
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
b = np.array([1, 10, 100])
b

array([  1,  10, 100])

In [60]:
b*x

array([[   0,   10,  200],
       [   3,   40,  500],
       [   6,   70,  800],
       [   9,  100, 1100]])

In [66]:
np.random.rand(100)

array([0.69846717, 0.00183663, 0.67287845, 0.13051475, 0.65084714,
       0.35345328, 0.0979802 , 0.68382316, 0.58910681, 0.92122756,
       0.5328045 , 0.46228565, 0.10387471, 0.6542588 , 0.21134681,
       0.68728328, 0.00916725, 0.13686761, 0.94525633, 0.11316239,
       0.10242705, 0.54022665, 0.09666397, 0.65040833, 0.46813879,
       0.81958015, 0.01495153, 0.75950285, 0.5668211 , 0.94099374,
       0.95476691, 0.96506128, 0.58223291, 0.22451123, 0.16156094,
       0.89913303, 0.02077762, 0.36485884, 0.847956  , 0.44656576,
       0.02410159, 0.83980766, 0.24127696, 0.66333838, 0.28689327,
       0.27428093, 0.41196163, 0.15135992, 0.05049862, 0.53855602,
       0.84238814, 0.84704243, 0.72249552, 0.77015703, 0.79963295,
       0.11636309, 0.55536163, 0.73901207, 0.61699432, 0.12223653,
       0.96729007, 0.31616112, 0.64668652, 0.67209938, 0.26763008,
       0.98965885, 0.38053458, 0.29934521, 0.78288023, 0.70119255,
       0.38593308, 0.29282625, 0.10400777, 0.32732073, 0.72802

In [39]:
x = np.arange(24).reshape((3,4,2))+1
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [43]:
np.pad(x, ((0,0),(1,1),(1,1)), 'constant')
# np.pad?

array([[[ 0,  0,  0,  0],
        [ 0,  1,  2,  0],
        [ 0,  3,  4,  0],
        [ 0,  5,  6,  0],
        [ 0,  7,  8,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  9, 10,  0],
        [ 0, 11, 12,  0],
        [ 0, 13, 14,  0],
        [ 0, 15, 16,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0, 17, 18,  0],
        [ 0, 19, 20,  0],
        [ 0, 21, 22,  0],
        [ 0, 23, 24,  0],
        [ 0,  0,  0,  0]]])

In [44]:
H, W = x.shape
for h in np.arange(H):
    for w in np.arange(W):
        print(x[1*h:1+1*h, 1*w:1+1*w])
        print('-'*30)

ValueError: too many values to unpack (expected 2)

In [46]:
x.shape

(3, 4, 2)

In [47]:
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [52]:
x[:, 0:3, :].shape

(3, 3, 2)

In [84]:
x = np.arange(4).reshape((2,2))+1
x

array([[1, 2],
       [3, 4]])

In [99]:
pad = 2
xpad = np.pad(x, pad, mode='constant')
xpad

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 3, 4, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [100]:
H, W = x.shape

In [102]:
xind = xpad[pad:H+pad, pad:W+pad]
xind

array([[1, 2],
       [3, 4]])

In [113]:
x[-4:9, 0:1]

array([[1],
       [3]])