In [15]:
import numpy as np

In [183]:
N, D, H = 3, 4, 5
x = np.linspace(-0.4, 1.2, num=N*D).reshape(N, D)
prev_h = np.linspace(-0.3, 0.7, num=N*H).reshape(N, H)
prev_c = np.linspace(-0.4, 0.9, num=N*H).reshape(N, H)
Wx = np.linspace(-2.1, 1.3, num=4*D*H).reshape(D, 4 * H)
Wh = np.linspace(-0.7, 2.2, num=4*H*H).reshape(H, 4 * H)
b = np.linspace(0.3, 0.7, num=4*H)

In [184]:
x_mat = np.dot(x, Wx)
h_mat = np.dot(prev_h, Wh)

activation = x_mat + h_mat + b

In [185]:
activation.shape

(3, 20)

In [189]:
i = activation[:, :5]
f = activation[:, 5:10]
o = activation[:, 10:15]
g = activation[:, 15:]

In [187]:
activation

array([[ 1.56210477,  1.52884119,  1.4955776 ,  1.46231401,  1.42905043,
         1.39578684,  1.36252325,  1.32925967,  1.29599608,  1.26273249,
         1.22946891,  1.19620532,  1.16294173,  1.12967815,  1.09641456,
         1.06315097,  1.02988739,  0.9966238 ,  0.96336021,  0.93009663],
       [ 0.52201728,  0.6412236 ,  0.76042992,  0.87963624,  0.99884256,
         1.11804888,  1.2372552 ,  1.35646152,  1.47566784,  1.59487416,
         1.71408048,  1.8332868 ,  1.95249312,  2.07169944,  2.19090576,
         2.31011208,  2.42931841,  2.54852473,  2.66773105,  2.78693737],
       [-0.51807021, -0.24639399,  0.02528224,  0.29695847,  0.5686347 ,
         0.84031092,  1.11198715,  1.38366338,  1.65533961,  1.92701583,
         2.19869206,  2.47036829,  2.74204451,  3.01372074,  3.28539697,
         3.5570732 ,  3.82874942,  4.10042565,  4.37210188,  4.64377811]])

In [190]:
i

array([[ 1.56210477,  1.52884119,  1.4955776 ,  1.46231401,  1.42905043],
       [ 0.52201728,  0.6412236 ,  0.76042992,  0.87963624,  0.99884256],
       [-0.51807021, -0.24639399,  0.02528224,  0.29695847,  0.5686347 ]])

In [191]:
f

array([[1.39578684, 1.36252325, 1.32925967, 1.29599608, 1.26273249],
       [1.11804888, 1.2372552 , 1.35646152, 1.47566784, 1.59487416],
       [0.84031092, 1.11198715, 1.38366338, 1.65533961, 1.92701583]])

In [192]:
o

array([[1.22946891, 1.19620532, 1.16294173, 1.12967815, 1.09641456],
       [1.71408048, 1.8332868 , 1.95249312, 2.07169944, 2.19090576],
       [2.19869206, 2.47036829, 2.74204451, 3.01372074, 3.28539697]])

In [193]:
g

array([[1.06315097, 1.02988739, 0.9966238 , 0.96336021, 0.93009663],
       [2.31011208, 2.42931841, 2.54852473, 2.66773105, 2.78693737],
       [3.5570732 , 3.82874942, 4.10042565, 4.37210188, 4.64377811]])

In [ ]:
next_h = output_gate * np.tanhh(next_c)

In [ ]:
tan_c = np.tanh(next_c)

In [ ]:
next_h = output_gate * tan_c

In [ ]:
def lstm_step_forward(x, prev_h, prev_c, Wx, Wh, b):
    """
    Forward pass for a single timestep of an LSTM.

    The input data has dimension D, the hidden state has dimension H, and we use
    a minibatch size of N.

    Note that a sigmoid() function has already been provided for you in this file.

    Inputs:
    - x: Input data, of shape (N, D)
    - prev_h: Previous hidden state, of shape (N, H)
    - prev_c: previous cell state, of shape (N, H)
    - Wx: Input-to-hidden weights, of shape (D, 4H)
    - Wh: Hidden-to-hidden weights, of shape (H, 4H)
    - b: Biases, of shape (4H,)

    Returns a tuple of:
    - next_h: Next hidden state, of shape (N, H)
    - next_c: Next cell state, of shape (N, H)
    - cache: Tuple of values needed for backward pass.
    """
    next_h, next_c, cache = None, None, None
    #############################################################################
    # TODO: Implement the forward pass for a single timestep of an LSTM.        #
    # You may want to use the numerically stable sigmoid implementation above.  #
    #############################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    # Unpacking dimensions
    N, H = prev_h.shape

    # Computing activation
    x_mat = np.dot(x, Wx)
    h_mat = np.dot(prev_h, Wh)

    activation = x_mat + h_mat + b

    # Computing i, f, o, g gates
    input_gate = sigmoid(activation[:, :H])
    forget_gate = sigmoid(activation[:, H:2*H])
    output_gate = sigmoid(activation[:, 2*H:3*H])
    gate_gate = np.tanh(activation[:, 3*H:])

    # Next cell state
    forget_c = forget_gate * prev_c
    ig_c = input_gate * gate_gate
    next_c = forget_c + ig_c

    # next_c = forget_gate * prev_c + input_gate * gate_gate

    # Next hidden state
    # next_h = output_gate * np.tanh(next_c)
    
    tanh_c = np.tanh(next_c)
    next_h = output_gate * tanh_c
    
    # Storing results in cache
    cache = (x, prev_h, Wx, Wh, b, prev_c, activation, input_gate, forget_gate, output_gate, gate_gate, next_c, tanh_c)
    
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ##############################################################################
    #                               END OF YOUR CODE                             #
    ##############################################################################

    return next_h, next_c, cache

In [ ]:
def rnn_forward(x, h0, Wx, Wh, b):
    """
    Run a vanilla RNN forward on an entire sequence of data. We assume an input
    sequence composed of T vectors, each of dimension D. The RNN uses a hidden
    size of H, and we work over a minibatch containing N sequences. After running
    the RNN forward, we return the hidden states for all timesteps.

    Inputs:
    - x: Input data for the entire timeseries, of shape (N, T, D).
    - h0: Initial hidden state, of shape (N, H)
    - Wx: Weight matrix for input-to-hidden connections, of shape (D, H)
    - Wh: Weight matrix for hidden-to-hidden connections, of shape (H, H)
    - b: Biases of shape (H,)

    Returns a tuple of:
    - h: Hidden states for the entire timeseries, of shape (N, T, H).
    - cache: Values needed in the backward pass
    """
    h, cache = None, None
    ##############################################################################
    # TODO: Implement forward pass for a vanilla RNN running on a sequence of    #
    # input data. You should use the rnn_step_forward function that you defined  #
    # above. You can use a for loop to help compute the forward pass.            #
    ##############################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    # Extracting dimensions
    N, T, D = x.shape
    N, H = h0.shape
    cache = {}
    
    # Setting up matrix with hidden states for entire timeseries
    h = np.zeros((N, T, H))
    h[:, 0, :] = h0

    # Iterating over every time dimension
    for t in range(T):
      
      # Extracting x for this time t
      x_iter = x[:, t, :]
      
      # Setting up previous hidden state
      if t==0:
        prev_h = h0
      else:
        prev_h = h[:, t-1, :]

      # Running an individual forward step
      next_h, cache_step = rnn_step_forward(x_iter, prev_h, Wx, Wh, b)

      # Storing results
      h[:, t, :] = next_h
      cache[t] = cache_step
    
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ##############################################################################
    #                               END OF YOUR CODE                             #
    ##############################################################################
    return h, cache

In [ ]:
def lstm_step_backward(dnext_h, dnext_c, cache):
    """
    Backward pass for a single timestep of an LSTM.

    Inputs:
    - dnext_h: Gradients of next hidden state, of shape (N, H)
    - dnext_c: Gradients of next cell state, of shape (N, H)
    - cache: Values from the forward pass

    Returns a tuple of:
    - dx: Gradient of input data, of shape (N, D)
    - dprev_h: Gradient of previous hidden state, of shape (N, H)
    - dprev_c: Gradient of previous cell state, of shape (N, H)
    - dWx: Gradient of input-to-hidden weights, of shape (D, 4H)
    - dWh: Gradient of hidden-to-hidden weights, of shape (H, 4H)
    - db: Gradient of biases, of shape (4H,)
    """
    dx, dprev_h, dprev_c, dWx, dWh, db = None, None, None, None, None, None
    #############################################################################
    # TODO: Implement the backward pass for a single timestep of an LSTM.       #
    #                                                                           #
    # HINT: For sigmoid and tanh you can compute local derivatives in terms of  #
    # the output value from the nonlinearity.                                   #
    #############################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    # Unpacking values from cache
    x, prev_h, Wx, Wh, b, prev_c, activation, input_gate, forget_gate, output_gate, gate_gate, next_c, tanh_c = cache
    N, H = dnext_h.shape

    # 1. next_h = output_gate * tanh_c 
    doutput_gate = tanh_c * dnext_h
    dtanh_c = output_gate * dnext_h

    # 2. tanh_c = np.tanh(next_c)
    dnext_c_down = (1 - np.tanh(next_c)**2) * dtanh_c
    dnext_c_total = dnext_c_down + dnext_c

    # 3. next_c = forget_c + ig_c
    dforget_c = dnext_c_total
    dig_c = dnext_c_total

    # 4. ig_c = input_gate * gate_gate
    dinput_gate = gate_gate * dig_c
    dgate_gate = input_gate * dig_c

    # 5. forget_c = forget_gate * prev_c
    dforget_gate = prev_c * dforget_c
    dprev_c = forget_gate * dforget_c

    # 6. Activations 
    dactivation_i = dinput_gate * sigmoid(activation[:, :H]) * (1 - sigmoid(activation[:, :H])) 
    dactivation_f = dforget_gate * sigmoid(activation[:, H:2*H]) * (1 - sigmoid(activation[:, H:2*H]))
    dactivation_o = doutput_gate * sigmoid(activation[:, 2*H:3*H]) * (1 - sigmoid(activation[:, 2*H:3*H]))
    dactivation_g = dgate_gate * (1 - np.tanh(activation[:, 3*H:])**2)
    dactivation = np.concatenate((dactivation_i, dactivation_f, dactivation_o, dactivation_g), axis=1)

    # 7. activation = x_mat + h_mat + b
    dx_mat = 1 * dactivation
    dh_mat = 1 * dactivation
    db = 1 * np.sum(dactivation, axis=0)

    # 8. x_mat = np.dot(x, Wx)
    dx = np.dot(dactivation, Wx.T)
    dWx = np.dot(x.T, dactivation)
    
    # h_mat = np.dot(prev_h, Wh)
    dprev_h = np.dot(dactivation, Wh.T)
    dWh = np.dot(prev_h.T, dactivation)

    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ##############################################################################
    #                               END OF YOUR CODE                             #
    ##############################################################################

    return dx, dprev_h, dprev_c, dWx, dWh, db

In [ ]:
def rnn_backward(dh, cache):
    """
    Compute the backward pass for a vanilla RNN over an entire sequence of data.

    Inputs:
    - dh: Upstream gradients of all hidden states, of shape (N, T, H). 
    
    NOTE: 'dh' contains the upstream gradients produced by the 
    individual loss functions at each timestep, *not* the gradients
    being passed between timesteps (which you'll have to compute yourself
    by calling rnn_step_backward in a loop).

    Returns a tuple of:
    - dx: Gradient of inputs, of shape (N, T, D)
    - dh0: Gradient of initial hidden state, of shape (N, H)
    - dWx: Gradient of input-to-hidden weights, of shape (D, H)
    - dWh: Gradient of hidden-to-hidden weights, of shape (H, H)
    - db: Gradient of biases, of shape (H,)
    """
    dx, dh0, dWx, dWh, db = None, None, None, None, None
    ##############################################################################
    # TODO: Implement the backward pass for a vanilla RNN running an entire      #
    # sequence of data. You should use the rnn_step_backward function that you   #
    # defined above. You can use a for loop to help compute the backward pass.   #
    ##############################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    # Unpacking dimensions and creating empty vectors
    N, T, H = dh.shape
    Wx = cache[0][2] # t=0, Wx is at index 2
    D, H = Wx.shape

    # Creating empty matrices
    dx = np.zeros((N,T,D))
    dh0 = np.zeros((N,H))
    dWx = np.zeros((D,H))
    dWh = np.zeros((H,H))
    db = np.zeros((H))
    dnext_h = np.zeros((N,H))

    # Iterating over time dimensions in reverse order
    for t in reversed(range(T)):
      
      # Upstream gradient from individual loss function
      dy = dh[:,t,:]
      
      # Combining horizontal and vertical gradients
      # (from next time step and from individual loss function)
      dh_all = dnext_h + dy
       
      # Running single backward step pass
      t_dx, dnext_h, t_dWx, t_dWh, t_db = rnn_step_backward(dh_all, cache[t])

      # Storing and updating results
      dx[:, t, :] = t_dx
      dh0 = dnext_h
      dWx += t_dWx
      dWh += t_dWh
      db += t_db

    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ##############################################################################
    #                               END OF YOUR CODE                             #
    ##############################################################################
    return dx, dh0, dWx, dWh, db

In [ ]:
def lstm_forward(x, h0, Wx, Wh, b):
    """
    Forward pass for an LSTM over an entire sequence of data. We assume an input
    sequence composed of T vectors, each of dimension D. The LSTM uses a hidden
    size of H, and we work over a minibatch containing N sequences. After running
    the LSTM forward, we return the hidden states for all timesteps.

    Note that the initial cell state is passed as input, but the initial cell
    state is set to zero. Also note that the cell state is not returned; it is
    an internal variable to the LSTM and is not accessed from outside.

    Inputs:
    - x: Input data of shape (N, T, D)
    - h0: Initial hidden state of shape (N, H)
    - Wx: Weights for input-to-hidden connections, of shape (D, 4H)
    - Wh: Weights for hidden-to-hidden connections, of shape (H, 4H)
    - b: Biases of shape (4H,)

    Returns a tuple of:
    - h: Hidden states for all timesteps of all sequences, of shape (N, T, H)
    - cache: Values needed for the backward pass.
    """
    h, cache = None, None
    #############################################################################
    # TODO: Implement the forward pass for an LSTM over an entire timeseries.   #
    # You should use the lstm_step_forward function that you just defined.      #
    #############################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    # Unpacking dimensions
    N, H = h0.shape
    N, T, D = x.shape
    cache = {}

    # Setting up initial values
    h          = np.zeros((N, T, H))
    h[:, 0, :] = h0

    # Iterating over every time dimension
    for t in range(T):

      # Selecting x for this time step
      x_t = x[:, t, :]

      # Setting up previous hidden state and cell state
      if t==0:
        prev_h = h0
        prev_c = np.zeros((N, H))
      else:
        prev_h = h[:, t-1, :]
        prev_c = next_c

      # Running individual forward step
      next_h, next_c, cache_t = lstm_step_forward(x_t, prev_h, prev_c, Wx, Wh, b)

      # Storing results
      h[:, t, :] = next_h
      cache[t] = cache_t

    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ##############################################################################
    #                               END OF YOUR CODE                             #
    ##############################################################################

    return h, cache


In [ ]:
def lstm_backward(dh, cache):
    """
    Backward pass for an LSTM over an entire sequence of data.]

    Inputs:
    - dh: Upstream gradients of hidden states, of shape (N, T, H)
    - cache: Values from the forward pass

    Returns a tuple of:
    - dx: Gradient of input data of shape (N, T, D)
    - dh0: Gradient of initial hidden state of shape (N, H)
    - dWx: Gradient of input-to-hidden weight matrix of shape (D, 4H)
    - dWh: Gradient of hidden-to-hidden weight matrix of shape (H, 4H)
    - db: Gradient of biases, of shape (4H,)
    """
    dx, dh0, dWx, dWh, db = None, None, None, None, None
    #############################################################################
    # TODO: Implement the backward pass for an LSTM over an entire timeseries.  #
    # You should use the lstm_step_backward function that you just defined.     #
    #############################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    # Unpacking dimensions
    N, T, H = dh.shape
    Wx = cache[0][2]
    D, H_4 = Wx.shape

    # Creating empty matrices
    dx = np.zeros((N,T,D))
    dh0 = np.zeros((N, H))
    dWx = np.zeros((D, 4*H))
    dWh = np.zeros((H, 4*H))
    db = np.zeros((4*H))
    dprev_h = np.zeros((N, H))
    dprev_c = np.zeros((N, H))

    # Iterating over time dimensions in reverse order
    for t in reversed(range(T)):

      # Upstream gradient from individual loss function
      dy = dh[:,t,:]

      # Combining horizontal and vertical gradients
      dh_all = dprev_h + dy

      # Running single backward pass
      t_dx, dprev_h, dprev_c, t_dWx, t_dWh, t_db = lstm_step_backward(dh_all, dprev_c, cache[t])

      # Storing and updating results
      dx[:, t, :] = t_dx
      dh0 = dprev_h
      dWx += t_dWx
      dWh += t_dWh
      db += t_db

    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ##############################################################################
    #                               END OF YOUR CODE                             #
    ##############################################################################

    return dx, dh0, dWx, dWh, db

In [ ]:
model = torchvision.models.squeezenet1_1(pretrained=True)


In [ ]:
def compute_saliency_maps(X, y, model):
    """
    Compute a class saliency map using the model for images X and labels y.

    Input:
    - X: Input images; Tensor of shape (N, 3, H, W)
    - y: Labels for X; LongTensor of shape (N,)
    - model: A pretrained CNN that will be used to compute the saliency map.

    Returns:
    - saliency: A Tensor of shape (N, H, W) giving the saliency maps for the input
    images.
    """
    # Make sure the model is in "test" mode
    model.eval()

    # Make input tensor require gradient
    X.requires_grad_()

    saliency = None
    ##############################################################################
    # TODO: Implement this function. Perform a forward and backward pass through #
    # the model to compute the gradient of the correct class score with respect  #
    # to each input image. You first want to compute the loss over the correct   #
    # scores (we'll combine losses across a batch by summing), and then compute  #
    # the gradients with a backward pass.                                        #
    ##############################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    
    # Computing scores for each class
    scores = model(X)
    
    # Obtaining scores corresponding to the true label
    scores_true = scores.gather(1, y.view(-1, 1)).squeeze()

    # Backpropagating to obtain gradient
    scores_true.backward(torch.Tensor([1,1,1,1,1]))

    # Obtaining absolute value of gradient
    grad = torch.abs(X.grad)

    # Take the maximum value over the 3 input channels
    saliency, saliency_idx = torch.max(grad, dim=1)

    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ##############################################################################
    #                             END OF YOUR CODE                               #
    ##############################################################################
    return saliency

In [ ]:
def make_fooling_image(X, target_y, model):
    """
    Generate a fooling image that is close to X, but that the model classifies
    as target_y.

    Inputs:
    - X: Input image; Tensor of shape (1, 3, 224, 224)
    - target_y: An integer in the range [0, 1000)
    - model: A pretrained CNN

    Returns:
    - X_fooling: An image that is close to X, but that is classifed as target_y
    by the model.
    """
    # Initialize our fooling image to the input image, and make it require gradient
    X_fooling = X.clone()
    X_fooling = X_fooling.requires_grad_()

    learning_rate = 1
    ##############################################################################
    # TODO: Generate a fooling image X_fooling that the model will classify as   #
    # the class target_y. You should perform gradient ascent on the score of the #
    # target class, stopping when the model is fooled.                           #
    # When computing an update step, first normalize the gradient:               #
    #   dX = learning_rate * g / ||g||_2                                         #
    #                                                                            #
    # You should write a training loop.                                          #
    #                                                                            #
    # HINT: For most examples, you should be able to generate a fooling image    #
    # in fewer than 100 iterations of gradient ascent.                           #
    # You can print your progress over iterations to check your algorithm.       #
    ##############################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    # Establishing number of iterations
    T = 100

    # Running loop over all iterations
    for t in range(T):

      # Forward pass
      scores = model(X_fooling)

      # Computing predicted y
      pred_y = torch.argmax(scores, dim=1)

      # If predicted y is the same as fooling y, we are done
      if pred_y[0] == target_y:
        break

      # Get the score for target_y
      target_score = scores[0][target_y]

      # Zeroing gradients before doing backward pass
      model.zero_grad()

      # Backward pass
      target_score.backward()

      grad = X_fooling.grad
      
      # Performing gradient ascent
      with torch.no_grad():
        grad = X_fooling.grad
        X_fooling += learning_rate * grad / grad.norm()
        
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ##############################################################################
    #                             END OF YOUR CODE                               #
    ##############################################################################
    return X_fooling

In [197]:
img = np.arange(9).reshape((3,3))

In [198]:
img

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [200]:
img[:-1, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [201]:
img[1:, :]

array([[3, 4, 5],
       [6, 7, 8]])

In [204]:
np.random.rand(1)

array([0.1643623])

In [ ]:
def discriminator_loss(logits_real, logits_fake):
    """
    Computes the discriminator loss described above.
    
    Inputs:
    - logits_real: PyTorch Tensor of shape (N,) giving scores for the real data.
    - logits_fake: PyTorch Tensor of shape (N,) giving scores for the fake data.
    
    Returns:
    - loss: PyTorch Tensor containing (scalar) the loss for the discriminator.
    """
    loss = None
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    # Obtaining dimension
    size = logits_real.shape[0]
    
    # Initializing true label vector
    true_labels = torch.ones(size).type(dtype)

    # First term - classifying the real image
    bce_real = bce_loss(logits_real, true_labels)
    bce_fake = bce_loss(logits_fake, 1 - true_labels)

    # Computing loss
    loss = bce_real + bce_fake

    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    return loss